### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by sirolf2009** [udevbe/wayland-java-bindings#1]
I've got a clean copy from git, and an up to date version of gradle, but when I run `sudo gradle install`, it fails to build. I'm running Ubuntu 14.04 LTS with java 1.7.0_75.

The output: http://pastebin.com/Rg2Z18RK

**Comment by Zubnix** [comment]
Hi, it looks like the generator is using a wrong type. Instead of 'WlObjectResource' or 'WlObjectProxy', it should use 'Resource' or 'Proxy'.

What version of libwayland do you have installed on your system? Could you provide me the contents of "/usr/share/wayland/wayland.xml"?

**Comment by Zubnix** [comment]
Looks like you're using libwayland 0.85 which has a "wl_object" interface as argument type in it's protocol xml. This has been removed since wayland 1.0. You should use a newer libwayland release.

**Comment by sirolf2009** [comment]
I believe I've updated wayland now (I'm still very new to this) but I'm still getting errors.
http://pastebin.com/XU9YQAEb
Is there any way to check my current wayland version?

**Comment by Zubnix** [comment]
Looks like you're trying to build Jekstrand's wayland java bindings. ( https://github.com/jekstrand/wayland-java ), or you're working on a very old checkout of this library (which originally started as a fork from those other bindings). 

Try doing a git pull on _this_ project and run it again. Alternatively you can wait until I published this project on maven central (I'm currently in the process of getting it there).

Checking which version you have is linux distro dependent, but I'll be your google for now:
http://askubuntu.com/questions/340530/how-can-i-check-the-available-version-of-a-package-in-the-repositories
