### ISSUE TITLE
Window doesn't get any inputs

### ISSUE THREAD

**Issue by daverix** [udevbe/wayland-java-bindings#9]
Steps to reproduce:
1. Run mvn install in root folder
2. Open Intellij and choose the pom.xml file in root
3. Edit the pom.xml file to include the examples module
4. Resync IDE with maven
5. Right click on main method in SimpleShm.java and choose run application
6. Try to click, right click, drag.

What happens:
- Nothing, clicks goes through the window to app below

What should happen:
- Window should swallow the clicks? I should be able to resize the surface?

I'm running Fedora 22 which have Wayland 1.7 installed and I'm running a wayland session.

**Comment by Zubnix** [comment]
Fix pushed. Tested on Weston. Can you confirm it works on gnome wayland (I assume that's what you are using)?

**Comment by daverix** [comment]
Yes it works in gnome now, Thanks! :)
